### ISSUE TITLE
Gaussian filter memory error

### ISSUE THREAD

**Issue by sshen82** [zhoujt1994/scHiCluster#19]
I want to do imputation on a 10kb dataset, and was trying the algorithm on one cell. However, it just shows the memory error like "MemoryError: Unable to allocate 278. GiB for an array with shape (273217, 273217) and data type float32". Do you have a solution on this? Do you think it is wise to skip the "pad" parameter to avoid gaussian_filter?

**Comment by sshen82** [comment]
Even if I set pad to be zero, np.triu_indices will give another memory error.

**Comment by zhoujt1994** [comment]
Do you need to do imputation on all-by-all chromosomes? We typically do it only within each chromosome, and when the resolution is high we only impute within a certain distance from the main diagonal. For example, when impute at 10kb resolution, we only do it for <5Mb. In general, I would not trust the imputation for trans or super long distance contacts at high resolution.
See https://zhoujt1994.github.io/scHiCluster/Tan2021/imputation.html

**Comment by sshen82** [comment]
That I agree and I switched to doing imputation chromosome by chromosome (only cis). However, now the problem is that the resulting matrices are pretty dense even after I directly filtered out interactions > 2mb. I have to run the jobs separately (like 8000 cells a time). It's also pretty slow. I have 50000 cells and for one night, only several hundred cells are done. I guess there isn't anything you can do now, since I am in the realm of 10kb, and everything is slow and huge there. Thank you for your advise though!

**Comment by zhoujt1994** [comment]
In our setting, we run the imputation on anvil supercomputer clusters, where each node has 128 cpus and it takes <8h to finish imputation of 1536 cells at 10kb resolution for <5Mb. And if you can use 40 such nodes in total, you can finish 60k cells overnight. If you want to do <2Mb it will be even faster. We works on 50-200k cells as a routine now which I think is not a huge problem. You can see our parameter settings in the link I sent above.
The storage could be an issue as you mentioned. I guess you need to prepare ~10T disk to store these cool files of 50k cells.

**Comment by sshen82** [comment]
Well, our university is poorer and the computational resources are limited, so even if I am using the high throughput computing system, it isn't as fast as yours :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by zhoujt1994** [comment]
Yes I agree. Sorry about that. Then I guess maybe change the output_dist, window_size, and step_size, these could make it faster. For example, output_dist=2000000, window_size=6000000, step_size=2000000 in your case.

**Comment by sshen82** [comment]
I see, that sounds great. Thank you for the advice!
________________________________
