### ISSUE TITLE
empty npv from embed-concat

### ISSUE THREAD

**Issue by csittz** [zhoujt1994/scHiCluster#5]
i used this 

hicluster embed-concatcell-chr --cell_list filelist.txt --outprefix concatdir/xx.250k --res 250000 --dim 2 --dist 20000000

but i get is empty file

NUMPY v {'descr': '<f8', 'fortran_order': True, 'shape': (10, 2), }
cat: write error: Input/output error

the embed-concatcell-chr say 0 cells loaded?

**Comment by yangmq6** [comment]
Sorry to bother you... I have the same problem and want to know how to solve it. Could you please give me some advice?

**Comment by csittz** [comment]
No I gave up using this.

Regards
Tony
________________________________

**Comment by yangmq6** [comment]
In my condition, because I just used less than 50 cells, less than the default dim number(50), the program can not run. The cell load just warns per 100 cells, so if the cell number is less than 100, you will just get "0 cells loaded"  even if your cells are loaded.
